# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-and-deploy-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to container registry
        run: |
          docker login https://ghcr.io -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_KEY}}
      - name: Build and push image to registry
        run: |
          docker buildxbuild --push -t ${{ secrets.DOCKER_TAG}} .

 
